// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
///
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApYGKnoi5KA8SdU4GuPJUZ6EKbJtyPlbU',
    appId: '1:1051890806510:web:f9fc17b38dea474b22cdff',
    messagingSenderId: '1051890806510',
    projectId: 'fir-provider-fe8e1',
    authDomain: 'fir-provider-fe8e1.firebaseapp.com',
    storageBucket: 'fir-provider-fe8e1.appspot.com',
    measurementId: 'G-3B8Z4CVP7S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKQSaQivgZplmI7Rg9schZA-PGH4QxuoQ',
    appId: '1:1051890806510:android:a08e29803d68a6ad22cdff',
    messagingSenderId: '1051890806510',
    projectId: 'fir-provider-fe8e1',
    storageBucket: 'fir-provider-fe8e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJxf9G8s1YgcaB1qw-0YebFb7HpUmE-3g',
    appId: '1:1051890806510:ios:876b1db5bf2dc24d22cdff',
    messagingSenderId: '1051890806510',
    projectId: 'fir-provider-fe8e1',
    storageBucket: 'fir-provider-fe8e1.appspot.com',
    iosBundleId: 'com.example.firebaseProvider',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJxf9G8s1YgcaB1qw-0YebFb7HpUmE-3g',
    appId: '1:1051890806510:ios:876b1db5bf2dc24d22cdff',
    messagingSenderId: '1051890806510',
    projectId: 'fir-provider-fe8e1',
    storageBucket: 'fir-provider-fe8e1.appspot.com',
    iosBundleId: 'com.example.firebaseProvider',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApYGKnoi5KA8SdU4GuPJUZ6EKbJtyPlbU',
    appId: '1:1051890806510:web:5d00de125591155b22cdff',
    messagingSenderId: '1051890806510',
    projectId: 'fir-provider-fe8e1',
    authDomain: 'fir-provider-fe8e1.firebaseapp.com',
    storageBucket: 'fir-provider-fe8e1.appspot.com',
    measurementId: 'G-HM81GF6JEQ',
  );
}
